kind: pipeline
name: Pipeline

steps:
- name: build
  image: golang
  commands:
  - go get -v -t -d ./...
  - go build
      
- name: testing
  image: golang
  commands:
  - go get -v -t -d ./...
  - go test -v ./...

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: dafg/droneci-workshop
    tags:
      - 1.1
      - latest
    compress: true
  when:
    branch:
      - master
